/// Flutter icons WeatherIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
///
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData one = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData four = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData three = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData eleven = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData nine = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData two = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData thirteen = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ten = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fifty = IconData(0xe80b, fontFamily: _kFontFam);
}
